-- MySQL Script generated by MySQL Workbench
-- Mon Nov 28 15:34:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema happy_home
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema happy_home
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `happy_home` DEFAULT CHARACTER SET utf8 ;
USE `happy_home` ;

-- -----------------------------------------------------
-- Table `happy_home`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `happy_home`.`cliente` ;

CREATE TABLE IF NOT EXISTS `happy_home`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(15) NOT NULL,
  `apellidoP` VARCHAR(20) NOT NULL,
  `apellidoM` VARCHAR(20) NOT NULL,
  `fechaReg` DATE NOT NULL,
  `tel` VARCHAR(14) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`));


-- -----------------------------------------------------
-- Table `happy_home`.`tiposPropiedad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `happy_home`.`tiposPropiedad` ;

CREATE TABLE IF NOT EXISTS `happy_home`.`tiposPropiedad` (
  `idTipo` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idTipo`));


-- -----------------------------------------------------
-- Table `happy_home`.`propiedad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `happy_home`.`propiedad` ;

CREATE TABLE IF NOT EXISTS `happy_home`.`propiedad` (
  `idPropiedad` INT NOT NULL AUTO_INCREMENT,
  `idTipo` INT NOT NULL,
  `propietario` INT NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `superficieT` FLOAT NOT NULL,
  `superficieC` FLOAT NOT NULL,
  `amueblada` VARCHAR(4) NOT NULL,
  `numRecamaras` INT NULL DEFAULT 1,
  `numNiveles` INT NULL DEFAULT 1,
  `numBaños` INT NULL DEFAULT 1,
  `mascotas` TINYINT NULL,
  `posesion` VARCHAR(9) NULL,
  `adjudicion` TINYINT NULL,
  `disponibilidad` TINYINT NULL,
  PRIMARY KEY (`idPropiedad`),
  INDEX `tipo_idx` (`idTipo` ASC) VISIBLE,
  INDEX `prop_idx` (`propietario` ASC) VISIBLE,
  CONSTRAINT `tipo`
    FOREIGN KEY (`idTipo`)
    REFERENCES `happy_home`.`tiposPropiedad` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `prop`
    FOREIGN KEY (`propietario`)
    REFERENCES `happy_home`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `happy_home`.`oferta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `happy_home`.`oferta` ;

CREATE TABLE IF NOT EXISTS `happy_home`.`oferta` (
  `idOferta` INT NOT NULL AUTO_INCREMENT,
  `idPropiedad` INT NOT NULL,
  `estado` VARCHAR(5) NOT NULL,
  `moneda` VARCHAR(7) NOT NULL,
  `precio` FLOAT NOT NULL,
  PRIMARY KEY (`idOferta`),
  INDEX `propiedad_idx` (`idPropiedad` ASC) VISIBLE,
  CONSTRAINT `propiedad`
    FOREIGN KEY (`idPropiedad`)
    REFERENCES `happy_home`.`propiedad` (`idPropiedad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `happy_home`.`rentas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `happy_home`.`rentas` ;

CREATE TABLE IF NOT EXISTS `happy_home`.`rentas` (
  `idOferta` INT NOT NULL,
  `idCliente` INT NOT NULL,
  `fechaInicio` DATE NOT NULL,
  PRIMARY KEY (`idOferta`, `idCliente`),
  INDEX `cliente_idx` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `oferta`
    FOREIGN KEY (`idOferta`)
    REFERENCES `happy_home`.`oferta` (`idOferta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `happy_home`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
